version: '3.7'
services:

  kurento:
    image: kurento/kurento-media-server:6.15
    network_mode: host


  kurento-rtmp:
    container_name: kurento-rtmp
    build:
      context: docker/kurento-rtmp
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./:/application/:rw
