version: '3.7'
services:

  kurento:
    image: kurento/kurento-media-server:6.15
    container_name: kurento
    ports:
      - "127.0.0.1:8888:8888"


  kurento-rtmp:
    container_name: kurento-rtmp
    build:
      context: docker/kurento-rtmp
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./:/application/:rw
